In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [22]:
df_ais = pd.read_csv(r"../data/raw/aisles.csv")
df_dep = pd.read_csv(r"../data/raw/departments.csv")
df_ord = pd.read_csv(r"../data/raw/orders.csv")
df_prod = pd.read_csv(r"../data/raw/products.csv")
df_opp = pd.read_csv(r"../data/raw/order_products__prior.csv")

In [23]:
df_ord.shape

(3421083, 7)

In [24]:
df_prod.shape

(49688, 4)

In [25]:
df_opp.shape

(32434489, 4)

In [26]:
df_ord.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [27]:
df_prod.head()

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

In [28]:
df_opp.head()

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [29]:
df_ais.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [30]:
df_ais.shape

(134, 2)

In [31]:
df_dep.shape

(21, 2)

In [32]:
df_dep.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

orders - Stores customer order history, 
order_products_prior - Stores products purchased in each order, 
products - Product master table, 
aisles - Product subcategory information, 
departments - Product category information,

In [33]:
for df_name, df in {
    "orders": df_ord,
    "order_products_prior": df_opp,
    "products": df_prod,
    "aisles": df_ais,
    "departments": df_dep
}.items():
    
    print(f"\n{'='*50}")
    print(df_name.upper())
    print('='*50)

    print(df.info())

==================================================
ORDERS
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   user_id                 int64
 2   eval_set                str
 3   order_number            int64
 4   order_dow               int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), str(1)
memory usage: 198.9 MB
None

==================================================
ORDER_PRODUCTS_PRIOR
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 32434489 entries, 0 to 32434488
Data columns (total 4 columns):
 #   Column             Dtype
---  ------             -----
 0   order_id           int64
 1   product_id         int64
 2   add_to_cart_order  int64
 3   reordered          int64
dtypes: int64(4)
memory usage: 989.8 MB
None

==================================================
PRODUCTS
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 49688 entries, 0 to 49687
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     49688 non-null  int64
 1   product_name   49688 non-null  str
 2   aisle_id       49688 non-null  int64
 3   department_id  49688 non-null  int64
dtypes: int64(3), str(1)
memory usage: 3.0 MB
None

==================================================
AISLES
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   aisle_id  134 non-null    int64
 1   aisle     134 non-null    str
dtypes: int64(1), str(1)
memory usage: 4.2 KB
None

==================================================
DEPARTMENTS
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   department_id  21 non-null     int64
 1   department     21 non-null     str
dtypes: int64(1), str(1)
memory usage: 638.0 bytes
None

In [34]:
for df_name, df in {
    "orders": df_ord,
    "order_products_prior": df_opp,
    "products": df_prod,
    "aisles": df_ais,
    "departments": df_dep
}.items():

    print(f"\n{df_name}")
    print(df.isnull().sum())

orders
order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

order_products_prior
order_id             0
product_id           0
add_to_cart_order    0
reordered            0
dtype: int64

products
product_id       0
product_name     0
aisle_id         0
department_id    0
dtype: int64

aisles
aisle_id    0
aisle       0
dtype: int64

departments
department_id    0
department       0
dtype: int64